### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#17]
I logged in under my dad's user and it is has been 5 minutes and is stuck on "exporting contacts" while logging in.

**Comment by jcaruso001** [comment]
Do you know how many contacts he has?

**Comment by Emmitts89** [comment]
He has probably 3,000 contacts on his phone. My mom has maybe 100, but I also cannot manually sync contacts on hers.

**Comment by jcaruso001** [comment]
Ok, 3,000 is quite a large set. Maybe instead of just showing a spinner we also show how many we have processed so far.

**Comment by Emmitts89** [comment]
Upon logging in, my mom's user got the error: "Unfortunately messagepro has stopped working"

**Comment by jcaruso001** [comment]
What android version and phone is she using?

**Comment by Emmitts89** [comment]
This is the Samsung Galaxy 3 device 4.3 android version

**Comment by Emmitts89** [comment]
Correction version is 4.4.2

**Comment by jcaruso001** [comment]
There's an issue with the API not having the same response between the successful and unsuccessful request, its in progress.

**Comment by Emmitts89** [comment]
Log in works, but it automatically logs into your profile because the email and password default to yours, I've put this on here before but it still has not been corrected.

**Comment by jcaruso001** [comment]
I understand what you mean, but please understand I log into this app thousands of times. It's a shorthand for me sorry. I left it in.

**Comment by jcaruso001** [comment]
I'll try and remember not to let it happen again.
