### ISSUE TITLE
Recap

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#18]
Blue dots do not go away on messages that are in recap

**Comment by Emmitts89** [comment]
After you respond to a message that is in the recap it was still staying in that folder

**Comment by jcaruso001** [comment]
Modified this to no longer drive off a "Read" status on the server that I don't use, but the local read status on the phone. Now you should see it as read, even if you read it on your main feed or on the recap feed, it will show that consistently.

**Comment by Emmitts89** [comment]
Blue dots are fixed! But now I responded to a message that was not responded too so it was showing in the recap, I did this through the main message screen, and I waited for a few minutes but it did not take that thread of the recap. I would say we waited about 5 minutes for it to go away and it did not.

**Comment by jcaruso001** [comment]
API Developer is looking into this.

**Comment by jcaruso001** [comment]
After sending a message I then mark all previous messages as read on the server so they don't end up on the recap.

**Comment by Emmitts89** [comment]
There is a “test user” in my recap folder but there is no test user in my main message screen and I cannot delete from recap folder. Also, no users are getting a recap reminder

**Comment by jcaruso001** [comment]
There's currently no functionality to delete items from recap and it wasn't part of the original api so you'll have to move that to version 2.

I'm moving recap reminders to its own issue.
