### ISSUE TITLE
Lock/Flag

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#20]
There is no way to unlock or unflag anything, it only flags or locks.

**Comment by jcaruso001** [comment]
That's completely my fault, in downloading the messages at different intervals i had to make sure it didn't reset the local falg and lock settings. Anyways I've fixed the flags and locks so you can flag and lock them again and see the icons in the chat view

![screenshot_2015-03-02-14-36-43](https://cloud.githubusercontent.com/assets/4194148/6449897/c99ef61a-c0e9-11e4-8888-59502e843123.png)

**Comment by Emmitts89** [comment]
Okay, I'll be testing the recent update tomorrow, but can you then unflag and unlock them as well now? And can you do it in either the main message thread or the lock folder or flag folder or both?

**Comment by Emmitts89** [comment]
1) Flag symbol should be the one with the flag colored in. 2) I figured out to unflag and unlock and it does work however, it is slightly confusing. Once you have flagged or locked a message and you are trying to unflag or unlock you have to hold down the message, the same overlay comes up that says "lock, flag, forward, copy". We either need to have it say unflag/unlock after it has a flag or a lock, or just have the user be able to unflag or unlock the message by tapping the flag or lock without any overlay coming up.

**Comment by jcaruso001** [comment]
Moving this to a new issue since the original bug is now resolved.
