### ISSUE TITLE
Forwarding

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#21]
Message forwarding does not work, it gives you the option to forward and to select the contact but then nothing happens after you select the contact you would like to forward it to. It should pull up the new message after you click the contact so that you can then send.

**Comment by jcaruso001** [comment]
I've resolved this, so now when you forward and select a user to forward it to the chat window will now show the forwarded message inside of the message area ready to send. However it did bring up another issue that was causing it where you couldn't open the message if you left it and attempted to come back in. Try and see if you get this error to after I fix it.

**Comment by Emmitts89** [comment]
I tried to re-create this and could not, forwarding worked and I could re-open thread.

**Comment by jcaruso001** [comment]
Verified.
