### ISSUE TITLE
Scheduled Messages

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#22]
Scheduled message time should be shown as regular time not military time.

**Comment by jcaruso001** [comment]
Changed the display date:

![screenshot_2015-03-02-16-26-45](https://cloud.githubusercontent.com/assets/4194148/6452128/0a3bea20-c0f9-11e4-8714-23c19028aba5.png)

**Comment by jcaruso001** [comment]
I will move additional request to separate issue.

**Comment by Emmitts89** [comment]
After you set up a schedule message and you look at it in your folder the time stamp at the bottom is not the actual time that you set it up for. I couldn't figure out what it was reflecting but it was not the time you selected, however it did send at the time you selected it for.

**Comment by jcaruso001** [comment]
Ah, it is the time except its in UTC/Zulu. I've formatted it better and it should work now.

**Comment by Emmitts89** [comment]
This is fixed.

**Comment by jcaruso001** [comment]
Verified.
