### ISSUE TITLE
Scheduled Messages Distrabution

### ISSUE THREAD

**Issue by jcaruso001** [Project-Caruso/MessagePro#23]
From my understanding the scheduled messages are showing up in the receivers scheduled messages folders. Rather than going to the main thread once it has passed the scheduled time.

**Comment by jcaruso001** [comment]
#22 : Moved this comment here.

 Also, The scheduled message I sent from Michaeleen to David only showed up in David's scheduled messages folder, not his main message thread with Michaeleen or on the main message screen. The scheduled message folder should only send from the scheduled message folder, the incoming message should be directed to the receivers main message threads.

**Comment by Emmitts89** [comment]
Your understanding is correct.

**Comment by Emmitts89** [comment]
The scheduled messages that have been successfully sent from the users phone should be removed from their scheduled message folder after.

**Comment by jcaruso001** [comment]
Fixed

**Comment by Emmitts89** [comment]
This is not working, I sent a scheduled message to Joe at 2:05 and he never received it and it is still in scheduled message folder

**Comment by jcaruso001** [comment]
API developer is looking into why they aren't converting from scheduled to normal.

**Comment by jcaruso001** [comment]
Scheduled messages should now disappear from the folder and show up in the messages list.

**Comment by Emmitts89** [comment]
Resolved.
