### ISSUE TITLE
Scheduled Message Cancellation

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#25]
So tonight I set up two separate scheduled messages and the first one got set up but had not sent and then I set up another one and it cancelled the first one out. They were sent to the same user (I'm limited on trying different users) but you should be able to set up more than one scheduled message to the same user without having it cancel the first one out, as well as have more than one scheduled message set up even if they are all going to different users.

**Comment by jcaruso001** [comment]
There's now a long click on each chat thread where you hold down the message thread and delete the thread from your active chats.

**Comment by jcaruso001** [comment]
Sorry there's currently no mechanism to delete a scheduled message. Stored messages are uploaded to the server once created, not just the local device. There's no call to remove this and didn't seem to be part of the previous API.
