### ISSUE TITLE
Deleting Messages & Threads

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#26]
There is no way to delete messages and threads that I have found. There's no edit button or swiping either way does not prompt anything for deleting it. In Proto.io we had set that up to be an edit button, due to the design now that might need to be altered because I believe we had it in the top left corner and now that is where the MessagePro icon is.

**Comment by jcaruso001** [comment]
That is an iOS only thing in the wireframe. There's now a long click on each chat thread where you hold down the message thread and delete the thread from your active chats.

**Comment by Emmitts89** [comment]
Deleting threads works, deleting individual messages inside a thread does not.

**Comment by jcaruso001** [comment]
Verified.
