### ISSUE TITLE
Thread Order

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#27]
Message threads were not in chronological order. We were doing a lot of forwarding and scheduled messaging but I tried to space it out for enough time for everything to update.

**Comment by jcaruso001** [comment]
The message thread now updates and sets the message thread list when sending messages and going back to the thread list.

**Comment by Emmitts89** [comment]
This is better but it still is lengthier than I would like to update. Any way to make this instantaneous or shorter? If not, hopefully it is something we can improve on in the future.

**Comment by jcaruso001** [comment]
I think it's something we'll have to improve on in the future.

Verified.
