### ISSUE TITLE
Flag Bug

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#28]
I flagged "football game" on my Mom's phone. This message was originally forwarded FROM my Dad's phone to my Mom. The flag then also showed up on my Dad's phone on that message that he forwarded.

**Comment by Emmitts89** [comment]
Also, When we were on my Mom's phone flagging and figuring out unflagging as well as locking/unlocking her's kept crashing stating "Unfortunately MessagePro has stopped working"

**Comment by jcaruso001** [comment]
Sounds be working now.

**Comment by Emmitts89** [comment]
I can't check this because of the flagging not working

**Comment by jcaruso001** [comment]
I'll work on this issue here.

**Comment by Emmitts89** [comment]
I sent forwarded message to Joe from our own conversation. He flagged and unflagged the message in his own thread earlier. When he received it, it messed up the order and the color from each of us in his main message thread. I will be adding a screen shot

**Comment by Emmitts89** [comment]
The forwarded messages always send out of order, under the last message that you sent even if the other user responded.

**Comment by jcaruso001** [comment]
Looks like the api is somehow adding an hour... having it looked into.

**Comment by jcaruso001** [comment]
This has been corrected on the API.

**Comment by Emmitts89** [comment]
No flag issues to report!
