### ISSUE TITLE
Lock/Unlock Verbiage

### ISSUE THREAD

**Issue by jcaruso001** [Project-Caruso/MessagePro#30]
Brought in from #20 

1) Flag symbol should be the one with the flag colored in
2) We need to have it say unflag/unlock after it has a flag or a lock

**Comment by jcaruso001** [comment]
Changed out the flag 
Just changed the labels to say the following for an easy fix:
    Flag / UnFlag
    Lock / UnLock

**Comment by Emmitts89** [comment]
The labels are changed but now flagging and unflagging and locking and locking do not work.

**Comment by jcaruso001** [comment]
Verified.
