### ISSUE TITLE
Scheduled Message Folder

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#31]
This has all previously scheduled and sent meeages stored in it, they should be removed when they are sent

**Comment by Emmitts89** [comment]
I sent a test message at 2:05 to Joe Grotto saying "test at 2:05"-> it showed up in my main message screen in the banner of our thread and gave me a blue dot but Joe never got the message and it was still in my scheduled message folder.

**Comment by jcaruso001** [comment]
When #23 is fixed this will resolve itself.
