### ISSUE TITLE
Locked Folder

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#32]
Can we only pull the locked message, not the entire thread into this folder? It's a pain to have to scroll through and find the locked message when you are in that folder

**Comment by Emmitts89** [comment]
Also, Joe deleted a thread in the Locked Folder and it deleted the whole thread from the folder, including the locked message. It deleted from the main message screen. Then when he started a new message with me in the main message screen it pulled up the old conversation but did not sync with the locked or flagged folders.

**Comment by jcaruso001** [comment]
Deleting a thread no longer deletes locked messages.

**Comment by Emmitts89** [comment]
Verified this and it does not delete locked message. No further lock issues to report.
