### ISSUE TITLE
Flagged Folder

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#33]
When you open the thread in this folder can it automatically open to the most recent flag? Same issue as locked, it is a pain to have to scroll through and find what it was that you flagged.

**Comment by Emmitts89** [comment]
Also, Joe deleted a thread in the Locked Folder and it deleted the whole thread from the folder, including the locked message. It deleted from the main message screen. Then when he started a new message with me in the main message screen it pulled up the old conversation but did not sync with the locked or flagged folders.

**Comment by Emmitts89** [comment]
Also, Joe deleted a thread in the Flagged Folder and it deleted the whole thread from the folder, including the locked & flagged messages in both folders. It deleted from the main message screen. Then when he started a new message with me in the main message screen it pulled up the old conversation but did not sync with the locked or flagged folders even though there were messages still marked.

**Comment by jcaruso001** [comment]
Flagged messages are allowed to be deleted right, just not locked correct?

**Comment by Emmitts89** [comment]
Correct

**Comment by jcaruso001** [comment]
Addressed in #32
