### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#37]
Joe and I both got this message when trying to upload a profile picture. With Joe, he couldn't select pictures from his entire gallery, only recent pictures, but it never updated. 

![joe-profile pic](https://cloud.githubusercontent.com/assets/10625873/6667171/5c362646-cbb8-11e4-881c-12fd41ef8dac.png)

**Comment by jcaruso001** [comment]
It was failing to allow the user to take photo's. I corrected this.

**Comment by Emmitts89** [comment]
I tried taking a picture and uploading and it froze and then closed, it also would not let me access the gallery to select a picture taken previously. Joe was able to take and upload a picture but could not select one from the gallery.

**Comment by jcaruso001** [comment]
I cannot reproduce this issue, please test it again and tell me the date and time you tested it that it failed.

**Comment by Emmitts89** [comment]
7:16/4/11/15- It does not give me option for Gallery, profile picture that I took in app DID work.

**Comment by jcaruso001** [comment]
Great, lets stick with just the picture taking for now and write up the gallery as an enhancement for later.
