### ISSUE TITLE
Message Sync

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#38]
While messaging, Joe and my conversation threads were not at all the same. He wasn't getting all the messages, when he would get them they would be out of chronological order, then it would switch on both of our phones to changing sides & color so it looked like he sent me a message that I sent him or vice versa.

![message sync 1-joe](https://cloud.githubusercontent.com/assets/10625873/6667380/9a5d7194-cbb9-11e4-982a-13bd4cb78e34.png)

![message sync 3-joe](https://cloud.githubusercontent.com/assets/10625873/6667392/af899aac-cbb9-11e4-9c45-618a0e57e150.png)
![message sync 2-joe](https://cloud.githubusercontent.com/assets/10625873/6667410/c6d34500-cbb9-11e4-8ad5-a2d04af60afb.png)

**Comment by jcaruso001** [comment]
I made some modifications, lets see if this makes things better.

**Comment by Emmitts89** [comment]
This was definitely improved from the last time but is still happening.My message thread is going back and forth between being synced and not synced correctly. Joe's was doing the same thing and his got worse when he would scroll through our convo.

**Comment by Emmitts89** [comment]
This is still happening a lot where our messages are going back and forth from being on the correct side or not.

**Comment by jcaruso001** [comment]
The order and sync seems to be working now with the gcm implementation.

**Comment by Emmitts89** [comment]
This is not working correctly. More of explanation in "Thread bug"

**Comment by jcaruso001** [comment]
Move to #44
