### ISSUE TITLE
Away Profile

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#42]
No auto response from my away profile was received by Joe. Eventually the response went into his recap folder but it is not in the main message thread.

I turned off away profile and then when I go back to the main messaging page it kept the overlay and I couldn’t do anything.

**Comment by jcaruso001** [comment]
Please do not combine multiple issues into one... 

I cannot reproduce the away profile not going away. Mine goes away whenever i turn it off successfully.

I have the API developer looking to the away message responses not coming in.

**Comment by jcaruso001** [comment]
The away profiles are now sent.

**Comment by Emmitts89** [comment]
They are sending but Joe is getting 2 at once.

**Comment by jcaruso001** [comment]
I beleive it was because the times were not correct, it seems to be working for me now.

**Comment by jcaruso001** [comment]
Verified
