### ISSUE TITLE
Recap Issue

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#43]
I responded to a thread in the recap to Joe and it sent to myself.

Then when I tried to open thread with Joe under recap folder it would not open our message it was just an empty screen and was not showing any of our messages.

**Comment by jcaruso001** [comment]
I'm not sure how to reproduce this. Seems to be working just fine for me.

**Comment by Emmitts89** [comment]
I will see if I can reproduce again with next update. If I can, do you need the date/time that the error occurred?

**Comment by jcaruso001** [comment]
Not unless it's a crash

**Comment by Emmitts89** [comment]
This didn't happen again
