### ISSUE TITLE
Thread Order

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#45]
The order of the threads on the main message screen is not correct for me now too.

**Comment by jcaruso001** [comment]
Can i get a screenshot?

**Comment by Emmitts89** [comment]
![image1](https://cloud.githubusercontent.com/assets/10625873/7150891/6900a478-e2e7-11e4-96d9-5747b19b62c6.JPG)

**Comment by jcaruso001** [comment]
I believe it was out of order due to the time not being GMT from the app...

**Comment by Emmitts89** [comment]
This is working now.

**Comment by jcaruso001** [comment]
Verfieied
