### ISSUE TITLE
Blue Dot

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#51]
Blue dot is back! When I logged out and then back in while trying to see if the rest of my contacts would show up, all of the messages I sent showed up with blue dots on the main message screen.

**Comment by jcaruso001** [comment]
The blue dots are stored locally... so if you log out you do a fresh download of everything and they are not read yet.

**Comment by Emmitts89** [comment]
These were for messages that I SENT, not that I received. The messages I received from you was read prior to logging out.
