### ISSUE TITLE
Reminder Setttings

### ISSUE THREAD

**Issue by Emmitts89** [Project-Caruso/MessagePro#7]
Nothing is there when I click on it

**Comment by jcaruso001** [comment]
The click event doesn't go anyways because I had a brain fart on what this was suppose to control.

**Comment by Emmitts89** [comment]
The reminder settings is for the flagged messaging reminders. 

Initially, I wanted it to have a date and time option so that when you held down and flagged the message it then came up with a screen that gave you the option to set the date and the time that then the reminder would pop up (like a push notification) that you needed to check that message.

Then you suggested that we just have a default for a time for all flagged messages to start with for the initial release. For example, the push notification would remind you for all flagged message in whatever duration of time you selected, such as an hour from when each message was flagged, or 3 hours from when flagged. The clock starts ticking when the message was flagged. Either of those are fine with me.

**Comment by Emmitts89** [comment]
This was supposed to be the default amount of time from when you flag a message. Right now it is set to a specific time, which doesn't really make any sense because then the user would have to go back in and set this after they have flagged the message every time. And it would not work if they have more than one flagged message. Instead, it should be the default time that would start ticking from the point that it was flagged. EX: 1 hour or two hours from when the message was flagged. This would then be the default for when the reminder would go off for each flagged message.

**Comment by Emmitts89** [comment]
Okay so I think this is working, but it looks like it is in military time if you don't really know what it supposed to be. I believe it was changed to 1 hour 2 hr ect with minutes as an additional option, but at the top we should probably add  "hours" or something after the duration is selected so it doesn't appear to be military time, rather it is a duration of time.

**Comment by jcaruso001** [comment]
This is not working, only the display was changed. I've modified the display even further to correct the time display on the screen once selected. I have yet to implement the reminder yet.

**Comment by jcaruso001** [comment]
Now the reminder notification shows up at the time we set.

**Comment by Emmitts89** [comment]
I still need to verify if a reminder comes up because I could not flag. Could we add hours/ minutes somewhere so it is clear that it is "Remind After: 1:00 hour" or something of that nature so it is not mistaken for a time like "Remind After: 1:00PM"

**Comment by jcaruso001** [comment]
Try again in the new version.

**Comment by Emmitts89** [comment]
The reminder works for flagged messages but clarity when setting time that it is duration of time rather than an actual time still needs to be added.

**Comment by jcaruso001** [comment]
You said that there should be a reminder after x hrs and x mins for flagged items not an actual time.

**Comment by Emmitts89** [comment]
Correct, and it is set up correctly. But on the label it should say something so that it is clear that it is a duration of time that you are setting, not an actual time. Does that clarify?

**Comment by jcaruso001** [comment]
Yes, you just tell me what to put there and i will.

**Comment by Emmitts89** [comment]
When you click on the alarm clock to scroll through the times, put hours or (hr) on the left side where the hours are and minutes or (min) no the right hand side.

**Comment by jcaruso001** [comment]
Done
